# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=20)),
                ('cat_description', models.TextField()),
                ('cat_url', models.CharField(max_length=200)),
                ('cat_disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
    ]
