# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 20:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20160327_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=20)),
                ('cat_description', models.TextField()),
                ('cat_disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='article_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='article',
            name='article_categorie',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='article.Categories'),
            preserve_default=False,
        ),
    ]
