# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20160329_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_url',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
