# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_title', models.CharField(max_length=20)),
                ('menu_description', models.TextField()),
                ('menu_url', models.CharField(max_length=20)),
                ('menu_disabled', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
